# `pandas'Series` and Data Frames

Review core methods to select data from a `pandas.DataFrame`.

See information about the data on [course website](https://meds-eds-220.github.io/MEDS-eds-220-course/book/chapters/lesson-3-pandas-subsetting/lesson-3-pandas-subsetting.html).

## Learning objectives
By the end of this lesson, students will be able to:

- Explain the relation between pandas.Series and pandas.DataFrame
- Construct simple pandas.Series and pandas.DataFrame from scratch using different initialization methods
- Perform simple operations on pandas.Series
- Navigate the pandas documentation to look for attributes and methods of pandas.Series and pandas.DataFrame

In [3]:
import pandas as pd
import numpy as np

# Series

A series is a one-dimensional array of indexed data.

A pandas.Series having an index is the main difference between a `pandas.Series` and a NumPy array.

In [9]:
# A numpy array
arr = np.random.randn(4) # random values from std normal distribution
print(type(arr))
print(arr, "\n")

# A pandas series made from the previous array
s = pd.Series(arr)
print(type(s))
print(s)

<class 'numpy.ndarray'>
[ 1.22993878  0.84105122  0.66836481 -0.54071358]

<class 'pandas.core.series.Series'>
0    1.229939
1    0.841051
2    0.668365
3   -0.540714
dtype: float64

# Creating a 'pandas.Series'

`s = pd.Series(data, index=index)`

The `data` parameter can be:
- a list or NumPy array
- a Python dictionary
- a single number, boolean (True/False), or string

`index` parameter is optional
If included it must be a list of indices of the same length as `data`
If we don't include it, the default is to make the index equal to `[0,...,len(data)-1]`

# Example: Creating a `pandas.Series` from a NumPy array
We need to pass a NumPy array (or a list of objects that can be converted to NumPy types) as `data`

In [6]:
# A series from a numpy array 
pd.Series(np.arange(3), index=[2023, 2024, 2025])

2023    0
2024    1
2025    2
dtype: int64

Example: Creating a `pandas.Series` from a list

In [7]:
# A series from a list of strings with default index
pd.Series(['EDS 220', 'EDS 222', 'EDS 223', 'EDS 242'])

0    EDS 220
1    EDS 222
2    EDS 223
3    EDS 242
dtype: object

# Example: Creating a pandas.Series from a dictionary
Dictionary: a set of key-value pairs. 

When creating a `pandas.Series` via a dictionary the keys will become the index and the values the corresponding data.

In [8]:
# Construct dictionary
d = {'key_0':2, 'key_1':'3', 'key_2':5}

# Initialize series using a dictionary
pd.Series(d)

key_0    2
key_1    3
key_2    5
dtype: object

In [ ]:
# An object in pandas usually indicates that the series is made up of strings. 
# Object data type can also be a mix of strings and numbers

# Example: Creating a `pandas.Series` from a single value

If we only provide a single number, boolean, or string as the data for the series, we need to provide an index. The value will be repeated to match the length of the index.

In [10]:
pd.Series(3.0, index = ['A', 'B', 'C'])

A    3.0
B    3.0
C    3.0
dtype: float64

# Simple Operations

Arithmetic operations and most NumPy functions work on series

Example:

In [11]:
# Define a series
s = pd.Series([98,73,65],index=['Andrea', 'Beth', 'Carolina'])

# Divide each element in series by 10
print(s /10, '\n')

# Take the exponential of each element in series
print(np.exp(s), '\n') # `\n` prints output to new line

# Original series is unchanged
print(s)

Andrea      9.8
Beth        7.3
Carolina    6.5
dtype: float64

Andrea      3.637971e+42
Beth        5.052394e+31
Carolina    1.694889e+28
dtype: float64

Andrea      98
Beth        73
Carolina    65
dtype: int64

In [12]:
# Showing that without `\n' output is printed on top of each other
s = pd.Series([98,73,65],index=['Andrea', 'Beth', 'Carolina'])

# Divide each element in series by 10
print(s /10)

# Take the exponential of each element in series
print(np.exp(s))

# Original series is unchanged
print(s)

Andrea      9.8
Beth        7.3
Carolina    6.5
dtype: float64
Andrea      3.637971e+42
Beth        5.052394e+31
Carolina    1.694889e+28
dtype: float64
Andrea      98
Beth        73
Carolina    65
dtype: int64

# Producing new `pandas.Series` with `True/False` values
Indicating whether the elements in a series satisfy a condition or not

In [13]:
s > 70

Andrea       True
Beth         True
Carolina    False
dtype: bool

# Identifying Missing Values
We can represent a missing, NULL, or NA value with the float value `numpy.nan`, which stands for "not a number"

In [14]:
# Series with NAs in it
s = pd.Series([1, 2, np.nan, 4, np.nan])
s

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
dtype: float64

In [15]:
# Check if series has NAs
s.hasnans

# The hasnans attribute returns `True` if there are any NA values

True

In [16]:
# The `isna` method gives as an output the elements in the series that are NA's

s.isna()

0    False
1    False
2     True
3    False
4     True
dtype: bool

# Check-In 1

The integer number -999 is often used to represent missing values. Create a pandas.Series named s with four integer values, two of which are -999. The index of this series should be the letters A through D.

In [27]:
s = pd.Series([80, -999, 35, -999], index = ['A','B','C','D'])
s

A     80
B   -999
C     35
D   -999
dtype: int64

In the pandas.Series documentation, look for the method mask(). Use this method to update the series s so that the -999 values are replaced by NA values. HINT: check the first example in the method’s documentation.

In [31]:
# Replace values where the condition is True `mask(cond[,other, inplace, axis, level])

s.mask(s==-999)

A    80.0
B     NaN
C    35.0
D     NaN
dtype: float64

# Data Frames

`pandas.DataFrame` represents tabular data (like a spreadsheet)
Each column of a `pandas.DataFrame` is a `pandas.Series`.

# Creating a `pandas.DataFrame

A `pandas.DataFrame` is a dictionary of `pandas.Series`, with each column name being the key and the column values being the key's value.

In [32]:
# Initialize dictionary with columns' data 
d = {'col_name_1' : pd.Series(np.arange(3)),
     'col_name_2' : pd.Series([3.1, 3.2, 3.3]),
     }

# Create data frame
df = pd.DataFrame(d)
df

   col_name_1  col_name_2
0           0         3.1
1           1         3.2
2           2         3.3

In [33]:
# We can change the index by changing the index attribute in the data frame
df.index = ['a','b','c']
df

   col_name_1  col_name_2
a           0         3.1
b           1         3.2
c           2         3.3

# Check-In 2
We can access the data frame’s column names via the columns attribute. Update the column names to C1 and C2 by updating this attribute.

In [38]:
df.columns= ['C1', 'C2']
df

   C1   C2
a   0  3.1
b   1  3.2
c   2  3.3

# Summary

`pandas.Series` is one dimensional indexed data

`pd.Series(data, index=index)`

If index is left empty the index starts 0, 1, ...
Index provides labels for values

Index can be a NumPy array, dictionary, single number, boolean, or string.

Arithmetic operations and functions can be used on series.

`numpy.nan` (`np.nan`) can be used to represent missing values

`.hasnans` returns True if there are NA values

`.isna()` returns True for NA values, False is not NA

`pandas.DataFrame` is tabular data, Each column is a `pandas.Series`

can use a `panda.Series` to create a series then apply p`anda.Dataframe` to create the dataframe from those series

Column names in a dataframe can be changed through

`df.index = ['']`
or
`df.columns = ['']`